// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuizApp.Repositories.EntityFramework.Concrete.Contexts;

#nullable disable

namespace Repositories.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250525125045_AddedNewMenusAndRoles")]
    partial class AddedNewMenusAndRoles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiService.Entities.Concrete.AppEntities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("FalseEntryCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserFullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 5, 25, 15, 50, 43, 399, DateTimeKind.Local).AddTicks(6606),
                            CreatedUserName = "Seed Data",
                            EmailConfirmed = true,
                            FalseEntryCount = 0,
                            IsActive = true,
                            IsBlocked = false,
                            ModifiedDate = new DateTime(2025, 5, 25, 15, 50, 43, 399, DateTimeKind.Local).AddTicks(6609),
                            ModifiedUserName = "Seed Data",
                            UserEmail = "berkayakar@gmail.com",
                            UserFullName = "Berkay AKAR",
                            UserName = "berkayakar",
                            UserPassword = "A665A45920422F9D417E4867EFDC4FB8A04A1F3FFF1FA07E998E86F7F7A27AE3"
                        });
                });

            modelBuilder.Entity("Core.Entities.Concrete.AppEntities.AppApplicationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppApplicationType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApplicationDescription = "MVC",
                            ApplicationName = "MVC",
                            CreatedDate = new DateTime(2025, 5, 25, 12, 50, 43, 396, DateTimeKind.Utc).AddTicks(1405),
                            CreatedUserName = "SeedData",
                            IsActive = true,
                            ModifiedDate = new DateTime(2025, 5, 25, 12, 50, 43, 396, DateTimeKind.Utc).AddTicks(1675),
                            ModifiedUserName = "SeedData"
                        },
                        new
                        {
                            Id = 2,
                            ApplicationDescription = "React",
                            ApplicationName = "React",
                            CreatedDate = new DateTime(2025, 5, 25, 12, 50, 43, 396, DateTimeKind.Utc).AddTicks(2585),
                            CreatedUserName = "SeedData",
                            IsActive = true,
                            ModifiedDate = new DateTime(2025, 5, 25, 12, 50, 43, 396, DateTimeKind.Utc).AddTicks(2585),
                            ModifiedUserName = "SeedData"
                        });
                });

            modelBuilder.Entity("Core.Entities.Concrete.AppEntities.AppMenus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppApplicationTypeId")
                        .HasColumnType("int");

                    b.Property<int>("AppClaimId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MenuDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MenuName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppApplicationTypeId");

                    b.HasIndex("AppClaimId");

                    b.ToTable("AppMenus");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Core.Entities.Concrete.AppEntities.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 5, 25, 15, 50, 43, 399, DateTimeKind.Local).AddTicks(2194),
                            CreatedUserName = "Seed Data",
                            IsActive = true,
                            ModifiedDate = new DateTime(2025, 5, 25, 15, 50, 43, 399, DateTimeKind.Local).AddTicks(2197),
                            RoleDescription = "En yetkili kullanıcı",
                            RoleName = "Sistem Admin"
                        });
                });

            modelBuilder.Entity("Core.Entities.Concrete.AppEntities.AppRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClaimId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.HasIndex("RoleId");

                    b.ToTable("AppRoleClaims");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimId = 1,
                            CreatedDate = new DateTime(2025, 5, 25, 15, 50, 43, 398, DateTimeKind.Local).AddTicks(9220),
                            CreatedUserName = "Sistem",
                            IsActive = true,
                            ModifiedDate = new DateTime(2025, 5, 25, 15, 50, 43, 398, DateTimeKind.Local).AddTicks(9224),
                            ModifiedUserName = "Sistem",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            ClaimId = 2,
                            CreatedDate = new DateTime(2025, 5, 25, 15, 50, 43, 398, DateTimeKind.Local).AddTicks(9516),
                            CreatedUserName = "Sistem",
                            IsActive = true,
                            ModifiedDate = new DateTime(2025, 5, 25, 15, 50, 43, 398, DateTimeKind.Local).AddTicks(9517),
                            ModifiedUserName = "Sistem",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 3,
                            ClaimId = 3,
                            CreatedDate = new DateTime(2025, 5, 25, 15, 50, 43, 398, DateTimeKind.Local).AddTicks(9520),
                            CreatedUserName = "Sistem",
                            IsActive = true,
                            ModifiedDate = new DateTime(2025, 5, 25, 15, 50, 43, 398, DateTimeKind.Local).AddTicks(9520),
                            ModifiedUserName = "Sistem",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 4,
                            ClaimId = 4,
                            CreatedDate = new DateTime(2025, 5, 25, 15, 50, 43, 398, DateTimeKind.Local).AddTicks(9522),
                            CreatedUserName = "Sistem",
                            IsActive = true,
                            ModifiedDate = new DateTime(2025, 5, 25, 15, 50, 43, 398, DateTimeKind.Local).AddTicks(9522),
                            ModifiedUserName = "Sistem",
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("Core.Entities.Concrete.AppEntities.AppUserRoles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("AppUserRoles");
                });

            modelBuilder.Entity("Entities.Concrete.AppEntities.AppClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppClaims");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimDescription = "Admin Layout içerisindeki Dashboard ın görülebilmesi için eklenmiş olan bir cliam dir.",
                            ClaimName = "Admin.Dashboard",
                            CreatedDate = new DateTime(2025, 5, 25, 12, 50, 43, 397, DateTimeKind.Utc).AddTicks(182),
                            CreatedUserName = "SeedData",
                            IsActive = true,
                            ModifiedDate = new DateTime(2025, 5, 25, 12, 50, 43, 397, DateTimeKind.Utc).AddTicks(183),
                            ModifiedUserName = "SeedData"
                        },
                        new
                        {
                            Id = 2,
                            ClaimDescription = "React uygulaması için yazılmış olan bir admin modül uygulamasıdır. ",
                            ClaimName = "React.Admin.AdminModule",
                            CreatedDate = new DateTime(2025, 5, 25, 12, 50, 43, 397, DateTimeKind.Utc).AddTicks(510),
                            CreatedUserName = "SeedData",
                            IsActive = true,
                            ModifiedDate = new DateTime(2025, 5, 25, 12, 50, 43, 397, DateTimeKind.Utc).AddTicks(511),
                            ModifiedUserName = "SeedData"
                        },
                        new
                        {
                            Id = 3,
                            ClaimDescription = "React uygulaması Admin Modül için kullanıcıların Listelendiği ekran ",
                            ClaimName = "React.Admin.AdminModule.Kullanici.Index",
                            CreatedDate = new DateTime(2025, 5, 25, 12, 50, 43, 397, DateTimeKind.Utc).AddTicks(513),
                            CreatedUserName = "SeedData",
                            IsActive = true,
                            ModifiedDate = new DateTime(2025, 5, 25, 12, 50, 43, 397, DateTimeKind.Utc).AddTicks(513),
                            ModifiedUserName = "SeedData"
                        },
                        new
                        {
                            Id = 4,
                            ClaimDescription = "React uygulaması Admin Modül için kullanıcıların Listelendiği ekran ",
                            ClaimName = "React.Admin.AdminModule.Kullanici.Roller",
                            CreatedDate = new DateTime(2025, 5, 25, 12, 50, 43, 397, DateTimeKind.Utc).AddTicks(515),
                            CreatedUserName = "SeedData",
                            IsActive = true,
                            ModifiedDate = new DateTime(2025, 5, 25, 12, 50, 43, 397, DateTimeKind.Utc).AddTicks(515),
                            ModifiedUserName = "SeedData"
                        });
                });

            modelBuilder.Entity("Entities.Concrete.AppEntities.AppToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.ToTable("AppTokens");
                });

            modelBuilder.Entity("Entities.Concrete.AppEntities.AppUserClaims", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClaimId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.HasIndex("UserId");

                    b.ToTable("AppUserClaims");
                });

            modelBuilder.Entity("Entities.Concrete.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedUserId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Core.Entities.Concrete.AppEntities.AppMVCMenus", b =>
                {
                    b.HasBaseType("Core.Entities.Concrete.AppEntities.AppMenus");

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ControllerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsNewTab")
                        .HasColumnType("bit");

                    b.Property<string>("MenuIcon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MenuOrderNumber")
                        .HasColumnType("int");

                    b.Property<string>("Parameter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RootId")
                        .HasColumnType("int");

                    b.HasIndex("RootId");

                    b.ToTable("AppMVCMenus", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Concrete.AppEntities.AppReactMenus", b =>
                {
                    b.HasBaseType("Core.Entities.Concrete.AppEntities.AppMenus");

                    b.Property<int>("MenuOrderNumber")
                        .HasColumnType("int");

                    b.Property<string>("MenuTextName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MenuTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RootId")
                        .HasColumnType("int");

                    b.HasIndex("RootId");

                    b.ToTable("AppReactMenus", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppApplicationTypeId = 2,
                            AppClaimId = 1,
                            CreatedDate = new DateTime(2025, 5, 25, 15, 50, 43, 397, DateTimeKind.Local).AddTicks(6808),
                            CreatedUserName = "Sistem",
                            IsActive = true,
                            MenuDescription = "React uygulaması giriş yapan kullanıcıyı karşılayan sayfa",
                            MenuName = "Dashboard",
                            ModifiedDate = new DateTime(2025, 5, 25, 15, 50, 43, 398, DateTimeKind.Local).AddTicks(4281),
                            ModifiedUserName = "Sistem",
                            MenuOrderNumber = 1,
                            MenuTextName = "DashBoard",
                            MenuTo = "/admin/dashboard"
                        },
                        new
                        {
                            Id = 2,
                            AppApplicationTypeId = 2,
                            AppClaimId = 2,
                            CreatedDate = new DateTime(2025, 5, 25, 15, 50, 43, 398, DateTimeKind.Local).AddTicks(5542),
                            CreatedUserName = "Sistem",
                            IsActive = true,
                            MenuDescription = "React uygulaması Admin Modül",
                            MenuName = "Admin Modül",
                            ModifiedDate = new DateTime(2025, 5, 25, 15, 50, 43, 398, DateTimeKind.Local).AddTicks(5544),
                            ModifiedUserName = "Sistem",
                            MenuOrderNumber = 1,
                            MenuTextName = "DashBoard",
                            MenuTo = ""
                        },
                        new
                        {
                            Id = 3,
                            AppApplicationTypeId = 2,
                            AppClaimId = 2,
                            CreatedDate = new DateTime(2025, 5, 25, 15, 50, 43, 398, DateTimeKind.Local).AddTicks(5548),
                            CreatedUserName = "Sistem",
                            IsActive = true,
                            MenuDescription = "React uygulaması Admin Modül Kullanicilar index sayfasi",
                            MenuName = "Kullanicilar",
                            ModifiedDate = new DateTime(2025, 5, 25, 15, 50, 43, 398, DateTimeKind.Local).AddTicks(5549),
                            ModifiedUserName = "Sistem",
                            MenuOrderNumber = 1,
                            MenuTextName = "DashBoard",
                            MenuTo = "/admin/adminmodul/kullanicilar"
                        },
                        new
                        {
                            Id = 4,
                            AppApplicationTypeId = 2,
                            AppClaimId = 2,
                            CreatedDate = new DateTime(2025, 5, 25, 15, 50, 43, 398, DateTimeKind.Local).AddTicks(5551),
                            CreatedUserName = "Sistem",
                            IsActive = true,
                            MenuDescription = "React uygulaması Admin Modül Roller index sayfasi",
                            MenuName = "Roller",
                            ModifiedDate = new DateTime(2025, 5, 25, 15, 50, 43, 398, DateTimeKind.Local).AddTicks(5552),
                            ModifiedUserName = "Sistem",
                            MenuOrderNumber = 1,
                            MenuTextName = "Roller",
                            MenuTo = "/admin/adminmodul/roller"
                        });
                });

            modelBuilder.Entity("Core.Entities.Concrete.AppEntities.AppMenus", b =>
                {
                    b.HasOne("Core.Entities.Concrete.AppEntities.AppApplicationType", "AppApplicationType")
                        .WithMany("AppMenus")
                        .HasForeignKey("AppApplicationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Concrete.AppEntities.AppClaim", "AppClaim")
                        .WithMany("AppMenus")
                        .HasForeignKey("AppClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppApplicationType");

                    b.Navigation("AppClaim");
                });

            modelBuilder.Entity("Core.Entities.Concrete.AppEntities.AppRoleClaim", b =>
                {
                    b.HasOne("Entities.Concrete.AppEntities.AppClaim", "AppClaims")
                        .WithMany("AppRoleClaims")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Concrete.AppEntities.AppRole", "AppRoles")
                        .WithMany("AppRoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppClaims");

                    b.Navigation("AppRoles");
                });

            modelBuilder.Entity("Core.Entities.Concrete.AppEntities.AppUserRoles", b =>
                {
                    b.HasOne("Core.Entities.Concrete.AppEntities.AppRole", "Role")
                        .WithMany("AppUserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiService.Entities.Concrete.AppEntities.AppUser", "AppUser")
                        .WithMany("AppUserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Entities.Concrete.AppEntities.AppToken", b =>
                {
                    b.HasOne("ApiService.Entities.Concrete.AppEntities.AppUser", "AppUser")
                        .WithOne("UserToken")
                        .HasForeignKey("Entities.Concrete.AppEntities.AppToken", "AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Entities.Concrete.AppEntities.AppUserClaims", b =>
                {
                    b.HasOne("Entities.Concrete.AppEntities.AppClaim", "AppClaim")
                        .WithMany("AppUserClaims")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiService.Entities.Concrete.AppEntities.AppUser", "AppUser")
                        .WithMany("AppUserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppClaim");

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Core.Entities.Concrete.AppEntities.AppMVCMenus", b =>
                {
                    b.HasOne("Core.Entities.Concrete.AppEntities.AppMenus", null)
                        .WithOne()
                        .HasForeignKey("Core.Entities.Concrete.AppEntities.AppMVCMenus", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Concrete.AppEntities.AppMVCMenus", "ParentMenu")
                        .WithMany("ChildMenus")
                        .HasForeignKey("RootId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentMenu");
                });

            modelBuilder.Entity("Core.Entities.Concrete.AppEntities.AppReactMenus", b =>
                {
                    b.HasOne("Core.Entities.Concrete.AppEntities.AppMenus", null)
                        .WithOne()
                        .HasForeignKey("Core.Entities.Concrete.AppEntities.AppReactMenus", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Concrete.AppEntities.AppReactMenus", "ParentMenu")
                        .WithMany("ChildMenus")
                        .HasForeignKey("RootId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentMenu");
                });

            modelBuilder.Entity("ApiService.Entities.Concrete.AppEntities.AppUser", b =>
                {
                    b.Navigation("AppUserClaims");

                    b.Navigation("AppUserRoles");

                    b.Navigation("UserToken")
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Entities.Concrete.AppEntities.AppApplicationType", b =>
                {
                    b.Navigation("AppMenus");
                });

            modelBuilder.Entity("Core.Entities.Concrete.AppEntities.AppRole", b =>
                {
                    b.Navigation("AppRoleClaims");

                    b.Navigation("AppUserRoles");
                });

            modelBuilder.Entity("Entities.Concrete.AppEntities.AppClaim", b =>
                {
                    b.Navigation("AppMenus");

                    b.Navigation("AppRoleClaims");

                    b.Navigation("AppUserClaims");
                });

            modelBuilder.Entity("Core.Entities.Concrete.AppEntities.AppMVCMenus", b =>
                {
                    b.Navigation("ChildMenus");
                });

            modelBuilder.Entity("Core.Entities.Concrete.AppEntities.AppReactMenus", b =>
                {
                    b.Navigation("ChildMenus");
                });
#pragma warning restore 612, 618
        }
    }
}
